version: 2.1

workflows:
      test-deploy:
          jobs:
            - test

jobs:
    test:
      docker:
          - image: cimg/python:3.13.1

      steps:
          - checkout
          - run: Run Python application
          - command: |
                  python app.py